### ISSUE TITLE
Investigate S3 API

### ISSUE THREAD

**Issue by fifthsegment** [fifthsegment/byos#29]
@Darthcedeus This task consists of 2 parts:

1- please investigate the ListObjects API call using the Postman APP. Here are the API Call templates: https://documenter.getpostman.com/view/9169647/UVeMGhwV#f63e5834-6821-474b-b175-4a63b6be92db
The credentials will be shared with you on Discord.
The goal of this task is to see if we can get the objects listed from the bucket via Postman using the S3 API (not B2) : 
Bucket: **testingbyos**
Region: **eu-central-003**

This bucket has only 2 objects stored inside it, so the call above should list them.

2- If it works with Postman, can you please investigate why it is failing for us here: 
We get a 403 error response back from the API and the browser says CORS failed because the HTTP status was not OK. Im at my wits end with this issue, need a fresh pair of eyes to take a look.

PR: https://github.com/fifthsegment/byos/pull/28
Preview: https://fifthsegment.github.io/byos/pr-preview/pr-28/#/login

**Comment by Darthcedeus** [comment]
The problem was backblaze API was blocking the request. Even if "_Share everything in this bucket with every origin_" is selected for CORS settings from the backblaze GUI, it will not allow all requests to go through. If this option is set, the following rules are enforced.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>authorization</AllowedHeader>
        <AllowedHeader>range</AllowedHeader>
        <MaxAgeSeconds>3600</MaxAgeSeconds>
    </CORSRule>
</CORSConfiguration>`

CORS configuration can be updated via backblaze command line tool. For testing & development I have configured CORS rule to allow everything. 

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
        <ExposeHeader>x-bz-content-sha1</ExposeHeader>
        <MaxAgeSeconds>3600</MaxAgeSeconds>
    </CORSRule>
</CORSConfiguration>`

**Comment by fifthsegment** [comment]
Perfect!
